### ISSUE TITLE
Project-management branch testing

### ISSUE THREAD

**Issue by okyeron** [monome/maiden#162]
Started testing the project-management branch and wanted to collect notes and start a discussion here.

Notes:
- would be nice to have the "hash" as a hotlink to the original source github page
- the hash number is on a new line from the script title - adds a bit of space. Seems like it would be cleaner to have it on one line.
![Screen Shot 2019-09-02 at 7 38 28 PM](https://user-images.githubusercontent.com/1909661/64136722-57f79d00-cdb9-11e9-82ab-f5dd4d38cb41.png)
- From the project-management page, clicking on the "gear" at the bottom kicks the main view over to the file viewer/REPL and does NOT bring up the configure/settings dialog until you click again.
- Could there be a "confirm" dialog when using `remove`?
- some kind of feedback would be nice when you click `update` (does this currently do anything?)
- I updated the community and lines sources json files, but the `available` tab is still blank in the web editor
- some padding at the bottom of the page listing for `installed` would be nice.
![Screen Shot 2019-09-02 at 7 49 26 PM](https://user-images.githubusercontent.com/1909661/64136970-cee16580-cdba-11e9-8b20-568171cc17be.png)

**Comment by ngwese** [comment]
Thanks for taking a look!

There is definitely fit and finish that needs work. Many of the points raised are already on the todo list here:
https://github.com/monome/maiden/projects/3

The main omission right now in my mind is indication of activity when doing update, remove, install etc.

Having the git hash link to the source should be doable, just need to verify that the major providers (github, gitlab, bitbucket, etc) have a consistent URL structure. In the installed view there isn't anything which ensures the source URL is http or that the repo in question is even on an accessible git server. The choice was intentional as some more technical folks will still do stuff manually on the device or would transfer project dirs to the device via sftp for example.

The odd spacing is a result of catalog entries lacking description and tag(s) metadata. Currently that can't be derived so most things don't have it. For manually constructed catalog one can add descriptions and tag which make the formatting appear. I don't have a good image handy but one can see the an older pass at the UI with one project having metadata here:
![image](https://user-images.githubusercontent.com/106652/64321846-3d1e5780-cf76-11e9-9552-28a0f2a6be29.png)

As far as things not updating after defining "community" and "lines" source configs I'm guessing the code on master doesn't yet have the refresh control added. My current working branch is here:
https://github.com/ngwese/maiden/commits/feature/project-polish

**Comment by ngwese** [comment]
Following up on this, I've added:
- confirmation dialogs on update and remove operations
- error dialogs if update or remove fails
- clicking the hash opens a new tab showing with the git URL used to download the project

Still to do:
- progress dialog on install and catalog sync operations

**Comment by tehn** [comment]
happy to test if you'd like to post a beta

**Comment by ngwese** [comment]
closing out since the core functionality has been released.
