### ISSUE TITLE
repl command should be echoed in output

### ISSUE THREAD

**Issue by ngwese** [monome/maiden#7]
would be nice to see the commands run in the output. ideally the would be formatted differently so that they stand out and clicking on them would copy the text down to the repl input

**Comment by synthetiv** [comment]
@ngwese I've been fiddling with other aspects of the REPL this weekend (#168), and since I've also felt the lack of differentiation between user-entered lines and program output, I thought I'd try adding some. My local copy of maiden now looks like this:

![image](https://user-images.githubusercontent.com/752281/66724598-d81c1400-edf5-11e9-88ee-98b630356ac6.png)

I'm not used to clicking previous lines to re-enter them in the input, but I can totally see how it would be useful, so I implemented that too.

Would you like a PR for this? And if so, it it OK for it to be part of one slightly bigger REPL-related PR? (also welcome styling suggestions!)

**Comment by ngwese** [comment]
Separate PRs is always nice but if you already have the work mixed in among another PR it isn't a big deal.

As far as styling I'm wondering if simply a darker color is enough - same color as the prompt text? Another option could be to also make the background for that entire echo'd input line slightly darker. One cool option with a darker background line is that it would provide enough visual guidance to allow us to add the ability to click on a historic input line in the repl and have the echoed back in the repl for re-evaluation.

Generally I'd favor a styling solve which didn't require indenting all the matron/sc output.

**Comment by synthetiv** [comment]
Good point that a different background would help lines look clickable. And with a different background, I think it will feel less necessary to indent everything else. I'll give it a try.
