### ISSUE TITLE
add url routing - open scripts from browser location url

### ISSUE THREAD

**Issue by artfwo** [monome/maiden#70]
and update the location url when a script is opened from the editor.

**Comment by ryanlaws** [comment]
What are the opinions on this now? Specifically I'm wondering what the static paths would look like. I'm thinking below `/maiden` there'd just be a `/dust`, so that e.g. `awake.lua` would work out to `http://norns.local/maiden/dust/awake/awake.lua`. For now, we could just handle paths starting with `/maiden/dust/`.

**Comment by ngwese** [comment]
Support for script URLs is now in master thanks to @ryanlaws
