### ISSUE TITLE
`ctrl+p` keybinding not working in some browsers

### ISSUE THREAD

**Issue by pq** [monome/maiden#71]
reported by @artfwo, `ctrl+p` does not work in:

* firefox / linux

i've also seen it not taking in:

* chrome / chrome os

**Comment by x2mirko** [comment]
I have the same issue on chrome / win10

**Comment by pq** [comment]
ah, thanks @x2mirko!

hey @anthonybarsotti: it occurs to me maybe you have some ideas here?  is it just a "browser thing" that some key events are not interceptable?

for context, key handling is happening here:

https://github.com/monome/maiden/blob/6224a34424b923fe3faf285673a1798631d88d81/app/src/services.js#L70-L78

with listening happening here:

https://github.com/monome/maiden/blob/6224a34424b923fe3faf285673a1798631d88d81/app/src/workspace.js#L56

**Comment by pq** [comment]
i wonder if trying the `editor.blur()` and `setTimeout()` trick described in https://github.com/ajaxorg/ace/issues/3179 isn't worth a shot...

**Comment by ryanlaws** [comment]
Same issue in Chromium / i3 on Arch

**Comment by ryanlaws** [comment]
It looks like the problem is that the keybinding provided in `services.js` applies to the window but does not define handing in the editor. I've had success in the default ACE editor by adding a `scriptRun` prop to the `Editor` class and adding the following prop to its JSX render-instantiation of the `AceEditor` class in `editor.js`: 
```
commands={[{
  name: 'play',
  bindKey: { win: 'Ctrl-P', mac: 'Ctrl-P' },
  exec: () => { 
    scriptRun && scriptRun(getActiveBuffer());
  }
}]}
```

Note that this does not appear to apply to the Vim keybindings (whose defaults oddly map this to `k` for moving up a line). I cannot speak for Emacs as I am completely incompetent in Emacs.

**Comment by ngwese** [comment]
Good to know - this is an area that hasn’t been touched in awhile. A PR which gets thing working would be most welcome
