### ISSUE TITLE
Preview for audio files?

### ISSUE THREAD

**Issue by simonvanderveldt** [monome/maiden#83]
Would it be possible/make sense to add a preview option for audio files?
The first thing I tried to do when I saw some preloaded samples is listen to them/preview them :)

**Comment by dndrks** [comment]
necrobump! with a slight reframe + extension :)

a support ticket came in that made a desire path clear: users assume that because the audio folder is present in maiden, that they can use maiden to download + upload audio. i know there are no UI elements that suggest it, but there isn't some sort of developer tool kung fu that'd open it up, right?

if this level of file management is interesting or worthwhile for maiden, then this is an FR for its inclusion.
if it isn't, then perhaps the audio folder should be removed from the file viewer, so as not to set up false expectations.

**Comment by ngwese** [comment]
the original ambition has always been to support drag/drop (or upload/download) to norns from the browser it has just never materialized.

despite the inability to preview/manipulate audio files there is still some value in exposing them in maiden. right now maiden might be the only way to remove potentially large audio files which contribute to a space crunch on the device without resorting to ssh, smb, or sftp.

**Comment by ngwese** [comment]
preview capability provided by #212
