### ISSUE TITLE
consider adding a way to trigger a device restart

### ISSUE THREAD

**Issue by pq** [monome/maiden#88]
it'd be great to provide a way to restart from maiden when something goes wrong on the device (e.g. `scsynth` dies).

naively, something like:

    os.execute("sleep 0.5; ./stop.sh; ./start.sh")

surfaced in a menu or on the config page or maybe just a more ergonomic command in the repl (like `norns.restart` or similar).

**Comment by ngwese** [comment]
Fixed by:
https://github.com/monome/maiden/commit/ea54691a7eec2262ff599c84095f758778985278
https://github.com/monome/maiden/commit/2e598507c1ea5e47aedbfe2e6369cbe2479c4f8e

Issuing `;restart` (or `;stop`, `;start`) in either matron or sc repl will cause the corresponding operation to be performs on the systemd service for matron or sc
